// Generated by CoffeeScript 1.10.0
(function() {
  var path;

  path = require('path');

  module.exports = function(robot, scripts) {
    robot.loadFile(require.resolve('hubot-auth').slice(0, -13), "index.coffee");
    return robot.loadFile(path.resolve(__dirname, "src", "scripts"), "heroku-commands.coffee");
  };

}).call(this);
